# Generated by Django 3.2.7 on 2022-01-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStart', models.DateTimeField(verbose_name='开始时间')),
                ('timeEnd', models.DateTimeField(verbose_name='结束时间')),
                ('name', models.CharField(max_length=50, verbose_name='开奖了嘛')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uWX', models.CharField(max_length=50, verbose_name='NULL')),
                ('uID', models.IntegerField(default=0)),
                ('uName', models.CharField(max_length=50)),
                ('uDep', models.CharField(max_length=50)),
            ],
        ),
    ]
