# Generated by Django 3.2.7 on 2022-01-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siginpro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uWX',
            field=models.CharField(max_length=50, null=True, verbose_name='NULL'),
        ),
    ]
